muety/wakapi

- .github/workflows/linux-build-on-release.yml
- .github/workflows/win-build-on-release.yml
This change makes it simpler for Windows users to use the project by automatically building the project with GitHub Actions on every release.
This allows for an easier way to use the project by automatically adding a zip file with the built executables to new releases.
Whenever you add a new Release, this GitHub Action will start and will build for Windows.
Example release:
As you can see, the built zip file is added automatically
> Automatically build the project for Windows users

- Dockerfile
- models/config.go
Allow modification of `base_path` through environment variable.
Happy to change `wait-for-it.sh` to modify `config.ini` instead also, if you're unhappy with the current approach.
> feat: add base_path environment variable

- Dockerfile
- docker-compose.yml
- main.go
- migrations/sqlite3/6_customrule_table.sql
- models/customrule.go
- models/heartbeat.go
- routes/heartbeat.go
- routes/settings.go
- services/custom_rule.go
- services/summary.go
- static/assets/app.js
- views/settings.tpl.html
- wait-for-it.sh
Hey there. I've been using this project for a while now and thought it would be great to let users input their own custom rules to changes the heartbeat's language based on the filename. While searching the code, I found something very similar [here](https://github.com/muety/wakapi/blob/177cbb12fcc46f9f63b4f65b482847eaad6e5f98/config.default.yml#L11) and thought it would be great to have a way to edit those rules on a per-user basis.
To do this, I added a custom_rule model and services and added endpoints to let the user create/delete them. Then, when an heartbeat is received, the rule is applied in the `Augment` function.
I was inspired by this (From wakatime):
Let me know what you think. BTW, are there any linter / code format tools I should be using for go? Should I use any of them …
> Add user-managed custom rules feature

- views/settings.tpl.html
Fix a very minor typo where the closing parens was missing.
> Added missing closing parens in language mapping description

- .github/workflows/docker.yml
- .github/workflows/linux-build-on-release.yml
- .github/workflows/win-build-on-release.yml
Resolves #110 
Reference:
https://github.com/marketplace/actions/build-and-push-docker-images#leverage-github-cache
https://github.com/marketplace/actions/build-and-push-docker-images#customizing
```
on:
push:
jobs:
a:
runs-on: ubuntu-latest
steps:
- run: echo "A=/etc/passwd" >> $GITHUB_ENV
- run: |
cat ${{ env.A }}
echo "hi"
```
runs successfully. 
Sample run:
https://github.com/YC/wakapi/runs/1821990900?check_suite_focus=true
https://github.com/YC/wakapi/actions/runs/533688180/workflow
Note: the correctness of L38-40 is uncertain
> ci(docker): Publish Docker Image on Release

- static/assets/app.js
Small one. I thought something was off with the scale... 
I'm not sure if this is the right fix for this, maybe we should use minutes instead of seconds? LMK if I should change it to show the time in minutes instead.
Probably closes #135
> Fixed scale label to show seconds instead of minutes

- views/summary.tpl.html
It is currently possible to enter a "End" date that is before the startdate, or a "start" date that is after the end date. This should prevent the user from directly entering an invalid date by setting a "min" and "max" value on those two date pickers.
There are no validation or the server's side, but that shouldn't be a problem since the invalid date will not create an error, it will simply return no data.
I've added a simple function that update the min and max values when the other input's value changes. I'm not sure if this is the cleanest way to go about this :thinking:
> Prevent invalid dates ranges in summary page

- models/heartbeat.go
I had troubles to get my `.blade.php` files recognised as `Blade` files. Therefore I changed the mapping algorithm to check for a suffix instead of using a regex to get the extension (after the last dot in the filename) and compare this extension to the custom mappings.
I think this is a more convenient way for any use cases and won't break anything.
> allow custom mappings with dot (issue #144)

- README.md
Updated the the links to the default config file, these were throwing a 404 error
> fix: README link to 'config.default.yml'

- main.go
@Tatsh can you please check?
I believe it is necessary to avoid `bind: address already in use`.
> fix: remove unix socket if exists

- utils/common.go
- utils/common_test.go
Hi, the version number of new [wakatime-cli](https://github.com/wakatime/wakatime-cli) (golang version) starts with `v`, like [v1.18.11](https://github.com/wakatime/wakatime-cli/releases/tag/v1.18.11).
So this regular expression needs to be updated to support it.
> Fix compatible with new wakatime-cli

- routes/compat/wakatime/v1/stats.go
- static/docs/docs.go
- static/docs/swagger.json
- static/docs/swagger.yaml
Hi there!
The parameter `range` of `/compat/wakatime/v1/users/{user}/stats/{range} [get]` is path.
However, it was described as query in OpenAPI-Docs.
So, I fixed it and generated files in `static/docs`.
Closes: #239
> fix(docs): wrong parameter in OpenAPI-Docs

- static/swagger-ui/index.html
Relevant for those hosting wakapi on subdirectory
Note: /swagger-ui redirects to /swagger-ui/
> fix: relative swagger-ui definition

- .github/workflows/docker.yml
> fix: anticipated docker push issue

- static/assets/js/summary.js
click project detail will redirect to a not exist page, when the service runs with a base path.
For example, the base path is `wakatime`,  and the dashboard uri will be `/wakatime/summary`. When click project detail, page will be redirect to `/wakatime/wakatime/summary?project=demo` but the correct detail page is `/wakatime/summary?project=demo`.
And i think `pushing a history stack` is better than `replace`, so that can back to dashboard by backwards.
> fix: href to a 404 when service on a subpath

- services/mail/smtp.go
I wasted like half hour because I used `WAKAPI_MAIL_SMTP_USERNAME` instead of `WAKAPI_MAIL_SMTP_USER`
Btw: Can we please add all env to the README. The sentence to look into the config doesn't help. It is in the config **username** and not **user**
> add error when no authentication is configured

- Dockerfile
- docker-compose.yml
the Dockerfile has a `VOLUME /data` defined. However, there are multiple reasons to skip this:
1) volumes can be (are expected to be?) defined when running with `docker run` or `docker-compose`
2) this volume is unnecessary and not useful if sqlite db backend is not being used
3) it is easier to define a volume as needed than to _undefine_ a hard-coded volume
4) this creates lots of stale volumes during repeated builds with docker or compose
also, [the readme](https://github.com/muety/wakapi#-option-3-use-docker) already shows a `docker run` command complete with volume definition, and the `docker-compose.yml` in this PR defines a persistent volume for db data.
> chore: remove hard-coded volume from Dockerfile

- models/interval.go
This PR add two identifier for the duration in the api. Because the ones for 12 months and any are [not like in Wakatime documentation](https://wakatime.com/developers#stats) and can cause error when using tools made for Wakatime.
For exemple [Metrics](https://github.com/lowlighter/metrics) uses [last_year](https://github.com/lowlighter/metrics/blob/7e4bab7d85c7d114cc928299765f830c107270a4/source/plugins/wakatime/index.mjs#L21) to get the data for 365 days.
> add last_year and all_time interval identifier like in wakatime docs

- config/config.go
- config/db.go
Allows specifiying a raw DSN (currently only used for dialect: postgres, not sure it makes sense for other database types). Resolves https://github.com/muety/wakapi/issues/423
> Add postgres DSN config option

- .github/workflows/ci.yml
- .gitignore
- testing/run_api_tests.sh
How it works:
1. Download release version of Wakapi
2. Run tests against release version
3. Run current build of wakapi
4. If the service can come up, it means that migrations succeeded
This PR also changes `run_api_tests.sh` to have two optional arguments database type and upgrade testing, which defaults to sqlite and no upgrade testing respectively. 
Part of #407
> Upgrade testing for SQLite

- repositories/metrics.go
Hello, I've just enabled metrics and noticed this warning, so I've prepared a fix.
> fix(metrics): warning - postgres - failed to get database size (expected 0 arguments, got 1)

- repositories/key_value.go
Remove ` to avoid syntax errors in PostgreSQL.
```
psql (15.3 (Debian 15.3-1.pgdg110+1))
Type "help" for help.
wakapi=> select * from key_string_values where `key` like '2021%';
ERROR:  operator does not exist: ` text
LINE 1: select * from key_string_values where `key` like '2021%';
^
HINT:  No operator matches the given name and argument type. You might need to add an explicit type cast.
wakapi=> select * from key_string_values where key like '2021%';
key                        | value
--------------------------------------------------+-------
20210213-add_has_data_field                      | done
20210221-add_created_date_column                 | done
20210411-add_imprint_content                     | done
20210202-fix_cascade_for_alias_user_constraint   | done …
```
> fix: invalid search query in Postgres

- .github/workflows/release.yml
ubuntu-18.04 has been deprecated.
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/
I think we downgraded to 18.04 at some point due to glibc, but this is perhaps not relevant any more after #408?
> ci(release): update to ubuntu-latest

- migrations/20221028_fix_heartbeats_time_user_idx.go
Fix an issue in migration which results in the following error message due to wrong and or precedence configuration:
```
panic: runtime error: index out of range [0] with length 0
```
> fix failing migration which prohibits startup

- .github/workflows/ci.yml
See "Use credentials that are minimally scoped" in https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-secrets
https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
Note that `GITHUB_TOKEN` does require more privileges for release actions (e.g. for pushing docker image). 
However, there's probably less risk there given that those pipelines are only triggered on release.
> ci: reduce permissions for non-release actions

- models/compat/wakatime/v1/project.go
- routes/compat/wakatime/v1/projects.go
Added fields in Project model for WakaTime compat API:
- `last_heartbeat_at`
- `human_readable_last_heartbeat_at`
- `urlencoded_name`
- `created_at`
I removed the `repository` field because I saw that there is no implementation. It used to return an empty string, which does not reflects the WakaTime implementation, because it's either null or an object. After #33 gets solved, I think it could be added again.
> feat: added fields in projects api

- testing/run_api_tests.sh
Reorder such that:
1. Run old version (initialisation for old db)
2. Run new version (migration test)
4. If sqlite (api tests)
1. populate data
2. Run new version again
3. Run api test
> fix: run api tests ordering

- models/compat/wakatime/v1/user.go
- Added the `photo` field in the User WakaTime model. It returns the URL for the avatar API used in the frontend.
- Replaced "Anonymous User" with the user id (should be more clear) in `display_name`
> feat: show avatar url in wakatime user model

- models/compat/wakatime/v1/user.go
When using an external API service (like Gravatar) the avatar URL returned from `/api/compat/wakatime/v1/users/current` is wrong: `http://localhost:3000/https://gravatar.com/avatar/3c90a086090c74081892efea2f523658`.
This PR checks if the returned URL from User.AvatarURL() is an URL or a path.
> fix: avatar url wrong url using external api

- config/config.go
Better to point automated API calls to the `api.wakatime.com` subdomain so they're load balanced.
> Use api subdomain for load balancing

- utils/collection_test.go
- utils/http.go
My KDE Kate installation with the officially endorsed plugin generates UA strings like `wakatime/ (Linux-6.XX-HOSTNAME-x86_64) KTextEditor/5.111.0 kate-wakatime/1.3.10`
> allow empty version in user agent regex for KDE Kate

- models/mail_address.go
- models/user.go
- scripts/email_checker.go
We should use `(*regexp.Regexp).MatchString` instead of `(*regexp.Regexp).Match([]byte(...))` when matching string to avoid unnecessary `[]byte` conversions and reduce allocations. A one-line change for free performance improvement.
Example benchmark:
```go
func BenchmarkMatch(b *testing.B) {
for i := 0; i < b.N; i++ {
if match := emailAddrRegex.Match([]byte("email@example.com")); !match {
b.Fail()
}
}
}
func BenchmarkMatchString(b *testing.B) {
for i := 0; i < b.N; i++ {
if match := emailAddrRegex.MatchString("email@example.com"); !match {
b.Fail()
}
}
}
```
Result:
```
goos: linux
goarch: amd64
pkg: github.com/muety/wakapi/models
cpu: AMD Ryzen 7 PRO 4750U with Radeon Graphics
BenchmarkMatch-16          	 1149106	      1012 ns/op	      24 B/op	       1 allocs/op
BenchmarkMatchString-16 …
```
> perf: avoid allocations with `(*regexp.Regexp).MatchString`

- .github/workflows/ci.yml
- .github/workflows/docker.yml
- .github/workflows/release.yml
Resolves #574 
Caching is on by default
https://github.com/actions/setup-go#caching-dependency-files-and-build-outputs
> ci: update actions, cache go dependencies

- README.md
In MacOS Sonoma error appears that the `tr` command is encountering some bytes in the `/dev/urandom` output that are not valid. The `/dev/urandom` device produces random bytes.
When you pipe this to tr, it expects input that is valid text in your current locale. However, urandom may produce bytes that are not valid.
The `LC_ALL=C` sets the locale to C, which handles any byte values. Now should not complain about illegal byte sequences anymore. This will generate a random alphanumeric string.
Tested on MacOS and Ubuntu. In the left picture is MacOS, the right is Ubuntu
So this doesn't break anything
> Updated SALT command syntax

- static/assets/js/components/entity-filter.js
The dropdown menus to filter for project, language, machine, and label are not working because the selection on the EntityFilter is not updated when selecting a new value. This PR set the selection from the event target.
> Fix entity filter

- .github/workflows/docker.yml
https://github.com/YC/wakapi/actions/runs/8493918515/job/23268493429
The output of tags seems correct:
```
/usr/bin/docker buildx build --file Dockerfile --iidfile /home/runner/work/_temp/docker-actions-toolkit-hxGaLq/iidfile --platform linux/amd64,linux/arm64 --provenance mode=max,builder-id=https://github.com/YC/wakapi/actions/runs/8493918515 --tag ghcr.io/yc/wakapi:2 --tag ghcr.io/yc/wakapi:2.11 --tag ghcr.io/yc/wakapi:2.11.0 --tag ghcr.io/yc/wakapi:latest --tag ghcr.io/yc/wakapi:alpine --tag ghcr.io/yc/wakapi:latest --tag n1try/wakapi:2 --tag n1try/wakapi:2.11 --tag n1try/wakapi:2.11.0 --tag n1try/wakapi:latest --tag n1try/wakapi:alpine --tag n1try/wakapi:latest --metadata-file /home/runner/work/_temp/docker-actions-toolkit-hxGaLq/metadata-file .
```
> Special Docker push for 2.11.0

- views/settings.tpl.html
This pull request add URL encoding and make the two badges a bit more distinct.
When I was looking at the Badge section under integration, I was confused as to why the same badge was being displayed two times, without realizing one was a direct link to the current instance and the other links to shields.io using your instance's data. By making them a bit distinct, it could help remove that confusion when users first look at this section.
Also, by changing the space by a URL-encoded space in the link, it wont breaks the link when a user try to copy the badge link somewhere else.
Before:
Copying the badge gives me ![badge](https://wakapi.notarock.lol/api/badge/notarock/notarock/interval:30_days?label=last 30d)
After:
Copying the badge gives me …
> Improve badge integration sections

- models/heartbeat.go
[Browser extension](https://github.com/wakatime/browser-wakatime) sends heartbeat in such format
```json
[
{
"branch": "<<LAST_BRANCH>>",
"category": "meeting",
"entity": "https://meet.google.com",
"id": "0014a80e-3a79-4bdd-a678-60e801ca7f58",
"plugin": "Google Meet",
"project": "xxx-xxxx-xxx",
"time": "1728043575.398",
"type": "domain",
"userAgent": "Chrome/129.0.0.0 mac_arm64 chrome-wakatime/4.0.2"
},
]
```
In wakapi there is 
```golang
type Heartbeat struct {
ID              uint64     `gorm:"primary_key" hash:"ignore"`
...
}
```
So we need use uuid or don't accept any id from client
There is second solution in this PR
> Ignore ID in incoming heartbeat requiest

- config/config.go
Closes #689 
When the configuration fails to load properly, an error gets logged using `Log()`. This logger requires the configuration to be loaded properly to function. Calling `Log().fatal` when a configuration loading error occurs causes a panic which obstructs the configuration error and confuses users.
By downgrading to use the built in `log` package when handling this error, we can get some pretty valuable info on why the configuration has failed to load.
Before:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x8 pc=0x104b276a0]
goroutine 1 [running]:
github.com/muety/wakapi/config.(*Config).IsDev(...)
/Users/notarock/src/wakapi/config/config.go:228
github.com/muety/wakapi/config.Log() …
```
> Remove circular dependency when logging configuration loading error

- models/heartbeat.go
Wakapi is a very useful tool, I have been using it to record my work time. Recently I found that Wakatime has some very useful fields that are very helpful for code analysis, but these fields are not recorded in Wakapi. This change is to add these fields in. 
These fields are
```
"dependencies": <string: comma separated list of dependencies detected from entity file (optional)>,
"lines": <integer: total number of lines in the entity (when entity type is file)>,
"line_additions": <integer: number of lines added since last heartbeat in the current file (optional)>,
"line_deletions": <integer: number of lines removed since last heartbeat in the current file (optional)>,
"lineno": <integer: current line row number of cursor with the first line starting at 1 (optional)>,
"cursorpos": <integer: …
```
> feat: add additional wakatime fields

- config/config.go
When the `TrustReverseProxyIps` configuration option is unset, it is `""` by default. Thus, this empty string is still parsed at startup, leading to an annoying warning:
```json
{"time":"2024-11-11T08:49:24.431844605Z","level":"WARN","msg":"failed to parse reverse proxy ip ranges"}
```
My fix is super simple, I decided to move it into the loop to also skip empty IPs within commas, for example when joining multiple IPs (like `10.x.x.x,,192.x.x.x`).
> fix(config): reverse proxy ip ranges parse warning when unset

- compose.yml
According to [`compose.yml`](https://github.com/muety/wakapi/blob/4f1b2d0a711c67ad7eb247308be61f3e6b96894f/compose.yml#L40) line 40, the appropriate environment variable to set the `smtp_pass` docker secret is `WAKAPI_SMTP_PASS`, not `WAKAPI_MAIL_SMTP_PASS`. I presume it's the README that needs to be changed, not the compose file itself - if `WAKAPI_MAIL_SMTP_PASS` is instead the desired environment variable name, let me know and I can update the PR accordingly.
> Update smtp_pass environment variable in compose.yml

- Dockerfile
In that way we utilize the cross compiling of Go, instead that we have to rely on QEMU.
This took on my machine 23s to build for all three arches.
https://www.docker.com/blog/faster-multi-platform-builds-dockerfile-cross-compilation-guide/
> ci: improve docker build speed

- helpers/interval.go
- helpers/interval_test.go
- helpers/summary.go
- migrations/20250818_add_start_of_week.go
- models/user.go
- repositories/user.go
- routes/api/metrics.go
- routes/compat/shields/v1/badge.go
- routes/compat/wakatime/v1/leaders.go
- routes/compat/wakatime/v1/stats.go
- routes/compat/wakatime/v1/statusbar.go
- routes/compat/wakatime/v1/summaries.go
- routes/settings.go
- routes/utils/badge_utils.go
- services/activity.go
- services/leaderboard.go
- utils/date.go
- views/settings.tpl.html
In the original WakaTime, there is an option to set the start of the week, but that option is missing here.
---
> feat: add user preference for start of week
