muety/wakapi

- .dockerignore
- Dockerfile
- moved some steps to the build stage to reduce number of final stage layers
- added more dotfiles into `.dockerignore`
> docker: reduce image layers

- .github/workflows/linux-build-on-release.yml
- .github/workflows/win-build-on-release.yml
> fix(ci): actions release, build on push/pr

- views/head.tpl.html
Closes #159 
Looks likes this:
> Add Open Graph meta tags

- scripts/sqlite2mysql.go
As a followup to #177 I fiddled with this script to migrate the data into postgres.
The way the postgres migration is currently fiddled in could probably be improved or dropped entirely since it adds additional obstacles (see point 4. -- for some reason the heartbeat id sequence was way off and caused errors on inserts on first start after the migration, not sure this holds for mysql as well).
Similar thing with the hash computation, not sure whether this was just an issue with my dataset or sqlite in general.
This 100 batching is however necessary, since the attempt to batch insert the entire dataset (~39k heartbeats in my case) fails for mysql and postgres.
For the former it complains about to many replacements in prepared statement, postgres complains about the exceeded number of …
> sqlitemigrate patches for larger datasets

- README.md
- config/config.go
- main.go
Can be tested with Netcat, socat, or [this code](https://gist.github.com/teknoraver/5ffacb8757330715bcbcc90e6d46ac74#file-unixhttpc-go).
> feat: 🎸 add support for using a UNIX domain socket

- .github/workflows/docker.yml
Reference:
https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md
> Build and push arm64 Docker image

- static/assets/app.js
- views/login.tpl.html
- views/summary.tpl.html
Resolves #232
```
Uncaught TypeError: Cannot set property 'innerHTML' of null
at summary:262
```
```js
document.getElementById('api-key-instruction').innerHTML = document.getElementById('api-key-container').value
```
And other errors from conditional rendering of data containers against 'no data available'.
> fix: ui errors from conditional HasData on summary

- main.go
- postman/Wakapi.postman_collection.json
- routes/compat/wakatime/v1/statusbar.go
- testing/Wakapi API Tests.postman_collection.json
I really wanted this feature, so i made it =)
I am not sure about project structure, I made the handler in right package?
Waka docs don't have any information about this endpoint, but I think it needs for this project in another PR
> Add statusbar endpoint (issue #244)

- .github/workflows/linux-build-on-release.yml
- .github/workflows/win-build-on-release.yml
- README.md
- testing/run_api_tests.sh
> feat: add test steps to Linux workflow

- models/compat/wakatime/v1/machine.go
- models/compat/wakatime/v1/user_agent.go
- services/imports/wakatime.go
This resolves issue https://github.com/muety/wakapi/issues/288.
> fix: consider all Machine/UserAgent entries

- .github/workflows/docker.yml
- Dockerfile
- entrypoint.sh
> Build linux/arm/v6 linux/arm/v7 Docker Images

- .github/workflows/docker.yml
Resolves #307
@muety Please also enable packages on home page
> ci: major and major.minor tags for Docker publish

- Dockerfile
Due to missing expose traefik cannot find the port of the webserver
> add missing expose to Dockerfile

- README.md
Personally, for me, it was slightly unclear which URL has to be pasted.
> elaborate on cloud server API URL

- .github/workflows/release.yml
Successful execution of first commit: https://github.com/muety/wakapi/actions/runs/2999385641
Not super confident about the release action, but hopefully works out...
Resolves #401
> Add more architectures to release binaries

- .github/workflows/release.yml
Resolves #403, #405.
The build is fine, but it's unclear whether the cross compilation works correctly without further testing.
https://github.com/muety/wakapi/actions/runs/3007275529
> Fix release by enabling cgo

- .github/workflows/ci.yml
- .github/workflows/release.yml
Artifacts: https://github.com/muety/wakapi/actions/runs/3158794080
> Remove gcc dependency in release

- routes/api/avatar.go
Avatar entropy is limited, increase entropy.
> Increase avatar entropy

- config/config.go
configor does not throw an error when the file is not there :)
> fix: remove config file requirement, fixes #435

- services/imports/wakatime.go
> fix: when importing from wakapi, os & editor are reversed

- .dockerignore
- Dockerfile
Resolves #464 
https://github.com/nodejs/docker-node/blob/main/19/alpine3.17/Dockerfile#L5-L6
https://github.com/nodejs/docker-node/blob/main/docs/BestPractices.md#non-root-user
> Non-root user for Docker

- config/config.go
- config/jobqueue.go
- main.go
- models/user_test.go
> feat: -version flag

- models/compat/wakatime/v1/data_dump.go
- services/imports/wakatime_dump.go
Adds on #503. @WangEdward, please check.
> Simplify import checks

- routes/compat/wakatime/v1/stats.go
> fix: ignore permissions when user is logged in stats api

- models/compat/wakatime/v1/summaries.go
> fix: crash on project summary

- repositories/summary.go
> Fix `SummaryItems` of type other than `Project` not persisted into DB when creating `Summary`

- repositories/summary.go
Fix #600.
See https://github.com/muety/wakapi/issues/600#issuecomment-1921723789
After applying the fix, run Regenerate Summaries from /settings#danger_zone.
> Fix summary page time not calculated correctly

- Dockerfile
Fields supported by GitHub:
- org.opencontainers.image.source
- org.opencontainers.image.description
- org.opencontainers.image.licenses
https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#labelling-container-images
The specification:
https://github.com/opencontainers/image-spec/blob/main/annotations.md
> Add annotations to Dockerfile

- .github/workflows/ci.yml
- services/mail/smtp_test.go
- testing/run_api_tests.sh
- testing/run_mail_tests.sh
> ci: run mail tests in workflow

- routes/settings.go
Fix "Sorry to you go" to "Sorry to see you go"
> Fix typo with account deletion

- README.md
usage for docker compose
maybe fix issues also for:
#526 
#649
> docs: Update README.md for docker compose usage

- views/summary.tpl.html
Updated ```summary.tpl.html``` tailwind classes to better support mobile views and be more responsive.
> Mobile Responsive

- services/mail/smtp.go
I need the ability to use smtp without authentication, so I made a small modification. Is that ok? Or should I do it differently?
> allow smtp with no auth

- routes/login.go
Closes #641
This is a quick and rough implementation to solve #641 
Please let me know what you think. Thanks.
> Improve error message when signing up a user with invalid name

- Dockerfile
> fix(ci): ARG for TARGETOS and TARGETARCH

- routes/leaderboard.go
> Remove debug log entry
